### ISSUE TITLE
ubi8/python question

### ISSUE THREAD

**Issue by shay-berman** [RHC4TP/starter#2]
Two questions about UBI base image.

1. Why you cannot create group\user with ubi8/python-36:1, while you can do it for generic ubi8/ubi image?   (I guess its related to the fact that ubi8/python-36 comes with defaultuser but with root permission)
2. Follow up question - what do you think is the best practice to set USER\GROUP in Dockerfile with ubi8/python-36 (or any other UBI application base image)?

ubi8 image run without issue:
```
#> kubectl run --rm -it --image=registry.access.redhat.com/ubi8/ubi:8.0 --restart=Never ubi8 -- /bin/sh -c 'groupadd -g 9999 appuser'
pod "ubi8" deleted

```
while ubi python cannot create group
```
# kubectl run --rm -it --image=registry.access.redhat.com/ubi8/python-36:1 --restart=Never ubi8 -- /bin/sh -c 'groupadd -g 9999 appuser'
groupadd: Permission denied.
groupadd: cannot lock /etc/group; try again later.
pod "ubi8" deleted

```

pod default/ubi8 terminated (Error)

Looks like that in the ubi python image there is none root default user 1001, probably this is the reason:
```
# kubectl run --rm -it --image=registry.access.redhat.com/ubi8/python-36:1 --restart=Never ubi8 -- /bin/sh -c 'id'
uid=1001(default) gid=0(root) groups=0(root)
pod "ubi8" deleted
```

Thanks

**Comment by jsm84** [comment]
You are correct that USER 1001 is used for the base python image, as the reason for not being able to create or delete users. The reason for this is that the ubi8/python image is an S2I builder image, intended to work with the `oc new-app` to build source hosted in an external git repo.

Setting USER 1001 in the Dockerfile is a common convention with S2I base images, but note that this gets overridden by default in OpenShift (by intent) unless a different Security Context Constraint is selected to allow running as a specific uid. Sometimes this causes issues with file permissions, as setting file/directory permissions to the user in the Dockerfile causes access denial when run as a randomized uid as in OpenShift. The way around this is to set the default group to root (gid 0), which grants no special permissions, but permissions can be set at the group level inside the container. The randomized uid will always be in the root group, using the default `restricted` SCC in OpenShift.

If you need to install additional packages to the ubi8/python image, then you'll need to set the USER to root (or `0`) in the Dockerfile, and the common convention is to set the USER back to 1001 once you've done that. A crude example:

```
FROM registry.access.redhat.com/ubi8/python-36:1

USER 0

RUN dnf install somepkg && \
    chmod 1001:0 /path/to/python/app

USER 1001
```

**Comment by shay-berman** [comment]
@jsm84 thanks for the quick answer and well detailed.

1. So just to confirm - by using ubi/python you suggest to avoid creating USER\GROUP for my application, instead it will get the default ubi/python USER 1001 and group 0.  Is this the right practice?

2. Usually the recommendation is to set none root user/group in the Dockerfile. I guess that the reason its less relevant for UBI/python is the assumption that the workload will run on Openshift which automatically set random UID when workload scheduled, right?

3. If you have a minute, let me know if this Dockerfile align with your guidelines:
    - https://github.com/IBM/ibm-block-csi-driver/blob/develop/Dockerfile-csi-controller 
    - https://github.com/IBM/ibm-block-csi-driver/blob/develop/Dockerfile-csi-node

Thanks a lot

**Comment by jsm84** [comment]
@shay-berman You're correct that the usual docker convention is not to set USER,  which then defaults to root unless run on OpenShift, which as stated runs as a random uid by default.Our general purpose base images conform to this wider docker convention of no USER being set. The exception to the rule are the S2I base images (python, php, ruby, etc), as they're essentially designed for use on OpenShift. The trick to getting around the random UID is to use the root group when setting permissions in the Dockerfile, as stated. USER 1001 is arbitrary and just an idiomatic convention for OpenShift images.You can break from either convention, if you like. If your app normally expects to be a certain username or uid, then you can certainly set that (note that you'd need to create the user account in the Dockerfile after becoming root, as shown previously). The only caveat to running as root or a set uid on OpenShift, is that your service account will require the 'anyuid' security context constraint applied (requires cluster-admin privilege in order to set). You just need to take this into consideration if you plan on supporting, say OpenShift Online, in which setting this SCC is not possible due to it being a multi-tenant environment due to security concerns.

**Comment by shay-berman** [comment]
Thanks @jsm84 for the clarifications about the python image.

Is there any Dockerfile best practice for ubi/ubi-minimal application that must run as `root` user? (in my case its needed root to discover block devices under /dev). 
In that case, is it recommanded to set `USER 0` in the Dockerfile  (of course that anyway the privileges in the pod [spec](https://github.com/IBM/ibm-block-csi-driver/blob/develop/deploy/kubernetes/v1.13/ibm-block-csi-driver.yaml#L344) is needed anyway, but my question is about best practice in Dockerfile for that case.).

**Comment by jsm84** [comment]
For ubi and ubi-minimal images (not the python image), you wouldn't explicitly set USER to 0 in the Dockerfile. There is no USER set in these base images, IIRC, which therefore would cause the default user to be root, if run with the proper Security Context Constraint (probably 'privileged' in that case) in OpenShift. You could try and force the user to run as root, but by default the restricted SCC would still prevent this. 

I would certainly test it first, but if the USER is set explicitly to root/0, then I believe the container will fail to run at all with the restricted SCC. If it's not explicitly set, then OpenShift will try and run it as the randomized uid (and the pod will probably fail in a crashloop due to permission issues when trying to access or write to /dev). I'm not 100% certain on the former case, which is why you should test it first. Sorry for not having a solid answer on that.

**Comment by jsm84** [comment]
@shay-berman Also, here are the more canonical guidelines for container development on OpenShift. These docs are for 3.x, but still apply to 4.x: https://docs.openshift.com/container-platform/3.11/creating_images/guidelines.html

I'll update as I find more.

**Comment by shay-berman** [comment]
Thanks a lot for the detail
Closing the ticket, since I have the relevant answers above.

Again thanks for the clarifications.
